import pandas as pd
import matplotlib.pyplot as plt
import os

# To run this script using using isolated environment (on macOS):
# cd Chapter_2-2
# python3 -m venv .venv
# source .venv/bin/active
# pip install pandas matplotlib
# python3 plot_mergesort.py
# deactivate

# get dir
script_dir = os.path.dirname(os.path.abspath(__file__))
output_dir = script_dir
file_name = 'mergesort_accesses.csv'
path = os.path.join(script_dir, file_name)

# Read the CSV generated by the Java program
df = pd.read_csv(path)

plt.figure(figsize=(10,6))
plt.plot(df['N'], df['TopDown'], label='Top-down accesses')
plt.plot(df['N'], df['BottomUp'], label='Bottom-up accesses')
plt.plot(df['N'], df['6NlgN'], label='6N log2 N (bound)')
plt.xlabel('Array size N')
plt.ylabel('Number of array accesses')
plt.title('Exact mergesort accesses vs 6N log2 N (1 ≤ N ≤ 512)')
plt.legend()
plt.grid(True)

# save image
save_name = "mergesort_accesses.png"
save_path = os.path.join(output_dir, save_name)
plt.savefig(save_path, dpi=150)
print(f"Saved plot to {save_path}")

plt.show()



